name: WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'   # runs daily at midnight UTC
  workflow_dispatch:       # lets you run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
